In [112]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/e99a526b2e7ccc6c3b70f53db43a87d2/raw/1605fc74aa778066bf2e6695e24d53cf65f2f447/machine-learning-carros-simulacao.csv"
dados = pd.read_csv(uri).drop(columns=["Unnamed: 0"], axis=1)
dados.head()

preco  vendido  idade_do_modelo   km_por_ano
0   30941.02        1               18  35085.22134
1   40557.96        1               20  12622.05362
2   89627.50        0               12  11440.79806
3   95276.14        0                3  43167.32682
4  117384.68        1                4  12770.11290

In [113]:
dados.shape

(10000, 4)

In [114]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

x = dados[["preco", "idade_do_modelo","km_por_ano"]]
y = dados["vendido"]

SEED = 158020
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25,
                                                         stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))


Treinaremos com 7500 elementos e testaremos com 2500 elementos


In [115]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier()
dummy_stratified.fit(treino_x, treino_y)
acuracia = dummy_stratified.score(teste_x, teste_y) * 100

print("A acurácia do dummy stratified foi %.2f%%" % acuracia)

A acurácia do dummy stratified foi 58.00%


In [116]:
from sklearn.tree import DecisionTreeClassifier

SEED = 158020
np.random.seed(SEED)
modelo = DecisionTreeClassifier(max_depth=2)
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)


A acurácia foi 71.92%


In [117]:
x = dados[["preco", "idade_do_modelo","km_por_ano"]]
y = dados["vendido"]

SEED = 5
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25,
                                                         stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = DecisionTreeClassifier(max_depth=2)
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)


Treinaremos com 7500 elementos e testaremos com 2500 elementos
A acurácia foi 76.84%


In [118]:
from sklearn.model_selection import cross_validate

SEED = 301
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 3, return_train_score=False)
media = results['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 3 = [%.2f, %.2f]" % ((media - 2 * desvio_padrao)*100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 3 = [74.99, 76.57]


In [119]:
SEED = 301
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 10, return_train_score=False)
media = results['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 10 = [%.2f, %.2f]" % ((media - 2 * desvio_padrao)*100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 10 = [74.24, 77.32]


In [120]:
SEED = 301
np.random.seed(SEED)

modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 5, return_train_score=False)
media = results['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 5 = [%.2f, %.2f]" % ((media - 2 * desvio_padrao)*100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 5 = [75.21, 76.35]


# Aleatoriedade no cross validate

In [121]:
from sklearn.model_selection import KFold

SEED = 301
np.random.seed(SEED)

cv = KFold(n_splits = 10)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)
media = results['test_score'].mean()
desvio_padrao = results['test_score'].std()
print("Accuracy com cross validation, 5 = [%.2f, %.2f]" % ((media - 2 * desvio_padrao)*100, (media + 2 * desvio_padrao) * 100))

Accuracy com cross validation, 5 = [74.37, 77.19]


In [122]:
from sklearn.model_selection import cross_validate

# Aleatoriedade
from sklearn.model_selection import KFold

cv = KFold(n_splits = 3)

In [123]:
def imprime_resultados(results):
    # É retornado em um dicionário do Python, então selecionarei apenas o test_score
    # Ele separou em 3, rodou o treino e o teste 3 vezes
    # .mean para obter a média
    media = resultados['test_score'].mean()
    
    # Desvio padrão
    desvio_padrao = resultados['test_score'].std()
    
    # Para obter o intervalo
    print("Accuracy média: %.2f" % (media * 100))
    print("Accuracy intervalo: [%.2f, %.2f]" % ((media - 2 *desvio_padrao) * 100, (media + 2 * desvio_padrao) * 100))

In [124]:
# Será passado X e y pois quem fará a estratificação do modelo é o próprio cross validate
resultados = cross_validate(modelo, x, y, cv = cv)

imprime_resultados(resultados)

Accuracy média: 75.78
Accuracy intervalo: [75.32, 76.24]


In [125]:
from sklearn.model_selection import cross_validate

# Utilizando o shuffle,ou seja, aleatoriedade
from sklearn.model_selection import KFold

cv = KFold(n_splits = 5, shuffle = True)

In [126]:
# Será passado X e y pois quem fará a estratificação do modelo é o próprio cross validate
resultados = cross_validate(modelo, x, y, cv = cv)

imprime_resultados(resultados)

Accuracy média: 75.78
Accuracy intervalo: [74.33, 77.23]


 # Estratificação com validação cruzada

## Simular situação de "azar" como pode ser uma proporção de exemplos desbalanceados entre as classes.

In [127]:
dados_azar = dados.sort_values('vendido', ascending =True)

x_azar = dados_azar[["preco", "idade_do_modelo","km_por_ano"]]
y_azar = dados_azar["vendido"]

dados_azar.head()

preco  vendido  idade_do_modelo   km_por_ano
4999  74023.29        0               12  24812.80412
5322  84843.49        0               13  23095.63834
5319  83100.27        0               19  36240.72746
5316  87932.13        0               16  32249.56426
5315  77937.01        0               15  28414.50704

In [128]:
# Sem o shuffle
from sklearn.model_selection import KFold

cv = KFold(n_splits = 10)
modelo = DecisionTreeClassifier(max_depth=2)
resultados = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 57.84
Accuracy intervalo: [34.29, 81.39]


In [129]:
# Com o shuffle
from sklearn.model_selection import KFold

cv = KFold(n_splits = 10, shuffle = True)
modelo = DecisionTreeClassifier(max_depth=2)
resultados = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 75.77
Accuracy intervalo: [72.87, 78.67]


In [130]:
# Com o StratifiedKFold ele consegue melhorar quando temos um desbalanceamento entre classes
from sklearn.model_selection import StratifiedKFold

cv = KFold(n_splits = 10, shuffle = True)
modelo = DecisionTreeClassifier(max_depth=2)
resultados = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 75.78
Accuracy intervalo: [73.65, 77.91]


# Gerando dados aleatórios de modelo de carro para simulação de agrupamentos ao usar nosso estimador

In [131]:
dados.head()

preco  vendido  idade_do_modelo   km_por_ano
0   30941.02        1               18  35085.22134
1   40557.96        1               20  12622.05362
2   89627.50        0               12  11440.79806
3   95276.14        0                3  43167.32682
4  117384.68        1                4  12770.11290

In [132]:
dados["idade_do_modelo"]

0       18
1       20
2       12
3        3
4        4
        ..
9995    12
9996    16
9997     4
9998     7
9999    19
Name: idade_do_modelo, Length: 10000, dtype: int64

In [133]:
len(dados)
# precisamos de um randint de tamanho 10000

10000

In [134]:
np.random.seed(SEED)
dados['modelo'] = dados['idade_do_modelo'] + np.random.randint(-2,3, size = 10000)
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo
0   30941.02        1               18  35085.22134      16
1   40557.96        1               20  12622.05362      22
2   89627.50        0               12  11440.79806      12
3   95276.14        0                3  43167.32682       4
4  117384.68        1                4  12770.11290       3

In [135]:
# modelo -1 fica estranho, então será mudado
dados['modelo'].unique()

array([16, 22, 12,  4,  3, 11, 18, 17, 13,  0, 15, 10,  9, 14,  1,  5, 19,
       21,  8,  7, 20,  6,  2, -1])

In [136]:
# será pego o menor dos valores e somar 1
abs(dados['modelo'].min())

1

In [137]:
dados['modelo'] = dados['modelo'] + abs(dados['modelo'].min()) + 1
dados.head()

preco  vendido  idade_do_modelo   km_por_ano  modelo
0   30941.02        1               18  35085.22134      18
1   40557.96        1               20  12622.05362      24
2   89627.50        0               12  11440.79806      14
3   95276.14        0                3  43167.32682       6
4  117384.68        1                4  12770.11290       5

In [138]:
dados.modelo.unique()

array([18, 24, 14,  6,  5, 13, 20, 19, 15,  2, 17, 12, 11, 16,  3,  7, 21,
       23, 10,  9, 22,  8,  4,  1])

In [139]:
dados.modelo.value_counts()

20    901
19    798
18    771
21    723
17    709
16    668
14    621
22    575
15    573
13    557
12    511
11    401
10    371
23    370
9     336
8     278
7     206
24    199
6     181
5     108
4      76
3      44
2      17
1       6
Name: modelo, dtype: int64

In [140]:
#######  NÃO DEVEMOS USAR #########
# Com o shuffle estaremos ignorando os agrupamentos
# Pois queremos um estimador que possa estimar um modelo de carro que o modelo não conheça ainda
cv = KFold(n_splits = 10, shuffle = True)
modelo = DecisionTreeClassifier(max_depth=2)
resultados = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 75.76
Accuracy intervalo: [73.15, 78.37]


# Testando  a validação cruzada com GroupKfold

In [141]:
# Com o GroupKFold ele considera os grupos, que são os grupos dos carros que foram criados
from sklearn.model_selection import GroupKFold

cv = GroupKFold(n_splits = 10)
modelo = DecisionTreeClassifier(max_depth=2)
resultados = cross_validate(modelo,
                            x_azar,
                            y_azar,
                            cv = cv,
                            groups = dados['modelo'],
                            return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 75.78
Accuracy intervalo: [73.67, 77.90]


# Cross Validation com StandardScaler

In [146]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [147]:
scaler = StandardScaler()

# Treino
scaler.fit(treino_x)
treino_x_escalado = scaler.transform(treino_x)
teste_x_escalado = scaler.transform(teste_x)

# Modelo
modelo = SVC()
modelo.fit(treino_x_escalado, treino_y)
previsoes = modelo.predict(teste_x_escalado)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 77.48%


In [148]:
# Com o GroupKFold ele considera os grupos, que são os grupos dos carros que foram criados
from sklearn.model_selection import GroupKFold

cv = GroupKFold(n_splits = 10)
modelo = SVC()
resultados = cross_validate(modelo,
                            x_azar,
                            y_azar,
                            cv = cv,
                            groups = dados['modelo'],
                            return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 77.27
Accuracy intervalo: [74.35, 80.20]


In [149]:
# Treino
scaler.fit(x_azar)
x_azar_escalado = scaler.transform(x_azar)


In [150]:
x_azar_escalado

array([[ 0.3636103 , -0.39591706,  0.24651152],
       [ 0.79214444, -0.18257669,  0.03346607],
       [ 0.72310419,  1.09746554,  1.66435195],
       ...,
       [ 0.17822399, -0.60925743, -0.73405662],
       [ 0.2248779 ,  0.45744443, -0.39741686],
       [-1.34266351,  0.88412517,  1.52099053]])

In [151]:
# Com o GroupKFold ele considera os grupos, que são os grupos dos carros que foram criados
from sklearn.model_selection import GroupKFold

cv = GroupKFold(n_splits = 10)
modelo = SVC()
resultados = cross_validate(modelo,
                            x_azar_escalado,
                            y_azar,
                            cv = cv,
                            groups = dados['modelo'],
                            return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 76.70
Accuracy intervalo: [74.30, 79.10]


In [156]:
from sklearn.pipeline import Pipeline

scaler = StandardScaler()
modelo = SVC()

pipeline = Pipeline([('transformação',scaler), ('estimador',modelo)])

cv = GroupKFold(n_splits = 10)
resultados = cross_validate(pipeline,
                            x_azar,
                            y_azar,
                            cv = cv,
                            groups = dados['modelo'],
                            return_train_score=False)
imprime_resultados(resultados)

Accuracy média: 76.68
Accuracy intervalo: [74.28, 79.08]
